site_name: SBM Docs
site_url: https://strqtz.codes/skyblockmodules/
site_author: Strqtz
docs_dir: skyblockmodulesdocs/docs
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: sbm
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate 
extra_css:
   - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Strqtz_
    - icon: fontawesome/brands/github
      link: https://github.com/Strqtz
    - icon: fontawesome/solid/globe-asia
      link: https://strqtz.codes
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets